### PR TITLE
March Composer mass update

### PR DESCRIPTION
**Pull request by N6REJ**
Adds phpunit to composer by default. Tests to be sure phpunit is installed when opening composer terminal
2.3.9
2.4.0
2.4.2
2.4.4
2.5.4
2.5.5
2.5.8
2.7.0 Security fix.
2.7.1
2.7.2
2.7.3
https://github.com/Bearsampp/module-composer/releases/tag/2024.4.5

### CODE REVIEW

**Comment by jwaisner** [comment]
Looks like the console is not recognizing the version change. Tested this on 2.5.8, 2.7.0 and 2.7.2 and it shows the console as the correct version but the version displayed that is actually running is the wrong version.

**Comment by jwaisner** [comment]
@N6REJ , putting this back on your list to check on.

**Comment by N6REJ** [comment]
> @N6REJ , putting this back on your list to check on.

ready for retest

**Comment by jwaisner** [comment]
Tested, version now matches but phpunit is only on 2.7.2 and 2.7.3. All other versions do not have phpunit.

**Pull request merged**
